@startuml
left to right direction

skinparam state {
  BackgroundColor White
  BorderColor Gray
}

[*] --> 0

state "R" as 0
state "ja" as 1

0:0
1:1

0 --> 0 : a:b
0 --> 0 : b:a
0 --> 1 : #

@enduml
