@startuml
'scale 350 width
left to right direction

skinparam state {
  BackgroundColor<<YES>> LightGreen
  BackgroundColor<<NO>> Red
  BorderColor Gray
}

[*] --> n0

state "nein" as n0 <<NO>>
state "nein" as n1 <<NO>>
state "nein" as n2 <<NO>>
state "nein" as n3 <<NO>>
state "ja" as j0 <<YES>>

n0: 0
j0: 1
n1: 2
n2: 3
n3: 4

'n0 --> j0: ab(a|b)*ab
n0 --> n2: a
n2 --> n1: b
n1 --> n1: a
n1 --> n1: b

n1 --> n3: a
n3 --> j0: b
@enduml
