@startuml
state "Endet auf a" as SA
state "Endet auf b" as SB
state "Endet auf ab" as SAB

SA: 0
SB: 1
SAB: 2

[*] --> SB

SA --> SA : a
SA --> SAB : b
SA --> [*] : nein

SB --> SA : a
SB --> SB : b
SB --> [*] : nein

SAB --> SA : a
SAB --> SB : b
SAB --> [*] : ja
@enduml
