@startuml
skinparam state {
  BackgroundColor<<YES>> LightGreen
  BackgroundColor<<NO>> Red
  BorderColor Gray
}

[*] --> 2

state "ein b" as 0 <<NO>>
state "zwei b" as 1 <<NO>>
state "drei b" as 2 <<YES>>

0: 0
1: 1
2: 2

0 --> 1 : b
0 --> 0 : a

1 --> 1 : a
1 --> 2 : b

2 --> 0 : b
2 --> 2 : a

@enduml
