@startuml

skinparam state {
  BackgroundColor<<YES>> LightGreen
  BackgroundColor<<NO>> Red
  BorderColor Gray
}

state "Endet auf a" as SA <<NO>>
state "Endet auf b" as SB <<NO>>
state "Endet auf ab" as SAB <<YES>>

SA: 0
SB: 1
SAB: 2

[*] --> SB

SA --> SA : a
SA --> SAB : b

SB --> SA : a
SB --> SB : b

SAB --> SA : a
SAB --> SB : b
@enduml
