@startuml
skinparam state {
  BackgroundColor<<YES>> LightGreen
  BackgroundColor<<NO>> Red
  BorderColor Gray
}

[*] --> 2

state "b" as 0 <<NO>>
state "bb" as 1 <<NO>>
state "bbb" as 2 <<YES>>

state "ab" as 3 <<NO>>
state "abb" as 4 <<NO>>
state "abbb" as 5 <<NO>>

0: 0
1: 1
2: 2
3: 3
4: 4
5: 5

0 --> 1 : b
0 --> 3 : a

1 --> 2 : b
1 --> 4 : a

2 --> 0 : b
2 --> 5 : a

3 --> 0 : a
3 --> 4 : b

4 --> 1 : a
4 --> 5 : b

5 --> 2 : a
5 --> 3 : b



@enduml
