@startuml
[*] --> 0

state "start" as 0

state "ein b" as 1
state "zwei b" as 2
state "drei b" as 3

0 --> 1 : b
0 --> 0 : a
'1 --> 2 : a

1 --> 2 : b
'2 --> 1 : b
1 --> 1 : a
2 --> 2 : a

2 --> 3 : b
3 --> 3 : a

3 --> 1 : b

@enduml
