@startuml
skinparam state {
  BackgroundColor<<YES>> LightGreen
  BackgroundColor<<NO>> Red
  BorderColor Gray
}

[*] --> s

state "start" as s <<YES>>

state "b" as 0 <<YES>>
state "bb" as 1 <<YES>>
state "bba" as 2 <<NO>>

s --> 0 : b
s --> s : a
0 --> 1 : b
0 --> s : a
1 --> 1 : b
1 --> 2 : a

2 --> 2 : a
2 --> 2 : b

0: 0
1: 1
2: 2
s: 3

@enduml
