@startuml
[*] --> 0

state "start" as 0

state "ein b" as 1
state "zwei b" as 2
state "drei b" as 3

0 --> 1 : b

1 --> 2 : b
1 --> 4 : a
4 --> 1 : a

2 --> 3 : b

3 --> 1 : b

2--> 5 : a
5 --> 2 : a

3 --> 6 : a
6 --> 3 : a

state "ein b" as 4
state "zwei b" as 5
state "drei b" as 6

0 --> 6 : a
4 --> 5 : b
5 --> 6 : b
6 --> 4 : b


0: 0
1: 1
2: 2
3: 3
4: 4
5: 5
6: 6


@enduml
