@startuml

skinparam state {
  BackgroundColor<<YES>> LightGreen
  BackgroundColor<<NO>> Red
  BorderColor Gray
}

[*] --> 0

state "start" as 0 <<NO>>

state "b" as 1 <<NO>>
state "a" as 2 <<NO>>
state "c" as 3 <<NO>>


state "b + c" as 5 <<NO>>
state "a + b" as 4 <<NO>>
state "a + c" as 6 <<NO>>
state "a + b + c" as 7 <<YES>>


0: 0
1: 1
2: 2
3: 3
4: 4
5: 5
6: 6


0 --> 1 : b
0 --> 2 : a
0 --> 3 : c
1 --> 1 : b
1 --> 4 : a
1 --> 5 : c
2 --> 2 : a
2 --> 4 : b
2 --> 6 : c
3 --> 5 : b
3 --> 3 : c
3 --> 6 : a

4 --> 4: a
4 --> 4: b
4 --> 7: c
5 --> 5: b
5 --> 5: c
5 --> 7: a
6 --> 6: a
6 --> 6: c
6 --> 7: b

7 --> 7: a
7 --> 7: b
7 --> 7: c

@enduml
