name: continuous build
on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Java 11 compile
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven compile
        run: mvn clean verify
      - name: upload docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: target/generated-docs
